import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/component/navBar";
import Footer from "@/component/Footer";
import InquiryForm from "@/component/main/InquiryForm";
import ChatWidget from "@/component/main/ChatWidget";
import Footer1 from "@/component/Footer1";
import NavNew from "@/component/main/NavNew";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Navbar */}
        {/* <div className="top-0 left-1/2 z-[100] absolute -translate-x-1/2 w-full max-w-[1400px] px-10 py-5 fixed"> */}
          {/* <NavBar /> */}
        <NavNew /> 
        {/* </div> */}

        {/* Page Content */}
        <main className="flex-grow ">{children}</main>

        {/* Footer */}
        {/* <Footer /> */}
        <Footer1 />
        <InquiryForm />
        <ChatWidget />
      </body>
    </html>
  );
}
